### ISSUE TITLE
Connection between nodes is not stable

### ISSUE THREAD

**Issue by mirceaalexandru** [rjrodger/seneca-mesh#13]
@rjrodger:

Using mesh in Concorda project.

when concorda-dashboard is using Concorda as microservice I have this problem:

 - first requests are correctly executed. After some requests (2-3) the connection is broken:

on Concorda-dashboard I have this error:

```
2016-02-19T11:33:28.632Z ma19ai76clxz/1455881573489/30993/- DEBUG	act	web       	IN	fb6gkr6nw6l0/ep267xz3c2on	do:startware,role:web	{req:{domain:{domain:null,_events:{},_eventsCount:1,_maxListeners:null,members:[],_disposed:null},_events:{},_e	ENTRY	(r4qzf)	-	-	-	
2016-02-19T11:33:28.635Z ma19ai76clxz/1455881573489/30993/- DEBUG	act	web       	OUT	fb6gkr6nw6l0/ep267xz3c2on	do:startware,role:web	null	EXIT	(r4qzf)	-	-	3	-	
2016-02-19T11:33:28.637Z ma19ai76clxz/1455881573489/30993/- DEBUG	act	concorda	IN	8apwys7bruk3/ep267xz3c2on	cmd:publicGetClient,role:concorda	{clientName:Concorda,cmd:publicGetClient,role:concorda}	ENTRY	(dumhh)	-	--	
2016-02-19T11:33:28.639Z ma19ai76clxz/1455881573489/30993/- DEBUG	act	client$       	IN	gu5hgprltht8/9ufh57zbmgyd	role:concorda-communication	{clientName:Concorda,cmd:publicGetClient,role:concorda-communication}	ENTRY	(6sgym)CLIENT	-	-	
2016-02-19T11:33:28.641Z ma19ai76clxz/1455881573489/30993/- DEBUG	-	-	ACT	gu37hjxfbldx/9ufh57zbmgyd	name:seneca-8t2tjw,plugin:define,role:seneca,seq:6,tag:undefined	plugin	concorda	ACT	va6abcmuqse8/9ufh57zbmgyd	name:balance-client,plugin:define,role:seneca,seq:10,tag:mesh~quxg7l	plugin	balance-client/mesh~quxg7l	client	send	seneca_role_concorda_communication__res	{type:balance,pin:role: concorda-communication,model:actor,id:kgi61q,role:transport,hook:client}	{did:(abtjg),fixedargs:{},context:{module:{id:/home/malex/workspace/nearForm/concorda-dashboard/node_modules/ch
2016-02-19T11:33:28.649Z ma19ai76clxz/1455881573489/30993/- ERROR	act	client$       	OUT		role:concorda-communication	9	{clientName:Concorda,cmd:publicGetClient,role:concorda-communication}	ENTRY	(6sgym)	-	seneca: no-target	no-target	{plugin:{}}	Error: seneca: no-target
    at errormaker (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/eraro/eraro.js:94:15)
    at Seneca.<anonymous> (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-balance-client/balance-client.js:159:27)
    at /home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-transport/lib/transport-utils.js:305:14
    at /home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-transport/lib/transport-utils.js:355:7
    at make_send (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-balance-client/balance-client.js:150:7)
    at /home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-transport/lib/transport-utils.js:350:5
    at Seneca.client.send (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-transport/lib/transport-utils.js:301:7)
    at Seneca.transport_client (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/chairo/node_modules/seneca/lib/transport.js:88:25)
    at actorModel (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-balance-client/balance-client.js:197:27)
    at Seneca.<anonymous> (/home/malex/workspace/nearForm/concorda-dashboard/node_modules/seneca-balance-client/balance-client.js:155:11)	
2016-02-19T11:33:28.651Z ma19ai76clxz/1455881573489/30993/- FATAL	-	-	ACT	gu37hjxfbldx/9ufh57zbmgyd	name:seneca-8t2tjw,plugin:define,role:seneca,seq:6,tag:undefined	plugin	concorda	ACT	zt83y62rkmwa/9ufh57zbmgyd	name:seneca-l1uklt,plugin:define,role:seneca,seq:8,tag:undefined	plugin	concorda-core-redirect	sys	seneca	1.1.0	ma19ai76clxz/1455881573489/30993/-	no-target	seneca: no-target	{plugin:{}}	all-errors-fatal
```

On the other mesh node I have this:

 - when request was correctly executed:

```
2016-02-19T11:33:16.952Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	concorda	IN	5usv479rayo8/9ufh57zbmgyd	role:concorda-communication	{clientName:Concorda,cmd:publicGetClient,role:concorda-communication}	ENTRY	(d4od5)	LISTEN	ma19ai76clxz/1455881573489/30993/-	-	
2016-02-19T11:33:16.953Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	concorda	IN	toycmdf95r6o/2cnaueltp16l	cmd:publicGetClient,role:concorda	{clientName:Concorda,cmd:publicGetClient,role:concorda}	ENTRY	(u4k1w)	LISTEN	ma19ai76clxz/1455881573489/30993/-	-	
2016-02-19T11:33:16.955Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	mem-store/1	IN	zqnr8n3oepqm/2cnaueltp16l	cmd:load,role:entity	{qent:{},q:{name:Concorda},cmd:load,role:entity,ent:{},name:data,base:client,zone:null}	ENTRY	(hs5rn)	-	-	-	
2016-02-19T11:33:16.956Z k2m4xbhk51te/1455881433977/30874/- DEBUG	-	-	ACT	qopisddi4yg4/1qadqqfhjo4u	name:seneca-4prqnu,plugin:define,role:seneca,seq:2,tag:undefined	plugin	mem-store/1ACT	zqnr8n3oepqm/2cnaueltp16l	cmd:load,role:entity	load	{name:Concorda}	-/client/data	{name:Concorda,configured:false,id:i7nrc7}	mem-store~1~-/-/-
2016-02-19T11:33:16.957Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	mem-store/1	OUT	zqnr8n3oepqm/2cnaueltp16l	cmd:load,role:entity	{name:Concorda,configured:false,id:i7nrc7}	EXIT	(hs5rn)	-	-	2	-	
2016-02-19T11:33:16.958Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	concorda	OUT	toycmdf95r6o/2cnaueltp16l	cmd:publicGetClient,role:concorda	{ok:true,data:{name:Concorda,configured:false,id:i7nrc7}}	EXIT	(u4k1w)	LISTEN	ma19ai76clxz/1455881573489/30993/-	5	-	
2016-02-19T11:33:16.958Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	concorda	OUT	5usv479rayo8/9ufh57zbmgyd	role:concorda-communication	{ok:true,data:{name:Concorda,configured:false,id:i7nrc7}}	EXIT	(d4od5)	LISTEN	ma19ai76clxz/1455881573489/30993/-	6	-
```

- when request was not OK
```
2016-02-19T11:33:28.853Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseIN	hfu2as82lpu0/0a6rnjlfikou	remove:client,role:transport,type:balance	{config:{port:58172,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY	(68sj7)	-	-	-	
2016-02-19T11:33:28.855Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseOUT	hfu2as82lpu0/0a6rnjlfikou	remove:client,role:transport,type:balance	null	EXIT	(68sj7)	-	-	3	-	
2016-02-19T11:33:29.001Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseIN	49xn26hguhf0/0a6rnjlfikou	remove:client,role:transport,type:balance	{config:{port:58948,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY	(68sj7)	-	-	-	
2016-02-19T11:33:29.002Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseOUT	49xn26hguhf0/0a6rnjlfikou	remove:client,role:transport,type:balance	null	EXIT	(68sj7)	-	-	2	-	
2016-02-19T11:33:29.076Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseIN	rekeagu97euf/0a6rnjlfikou	remove:client,role:transport,type:balance	{config:{pin:null:true},role:transport,type:balance,remove:client}	ENTRY	(68sj7)	-	-	-	
2016-02-19T11:33:29.078Z k2m4xbhk51te/1455881433977/30874/- DEBUG	act	balance-client/mesh~ukatseOUT	rekeagu97euf/0a6rnjlfikou	remove:client,role:transport,type:balance	null	EXIT	(68sj7)	-	-	2	-
```

**Comment by mirceaalexandru** [comment]
This is when I used seneca-mesh@0.4.0

I tried a downgrade after on 0.5.0 I have same behavior.

**Comment by mirceaalexandru** [comment]
this is from seneca-mesh@0.5.0:

```
2016-02-19T11:47:54.137Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	IN8zki46wfsif3/5fjojynzb98c	remove:client,role:transport,type:balance	{config:{port:53598,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY	(bscdw)	-	--	
2016-02-19T11:47:54.141Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	OUT8zki46wfsif3/5fjojynzb98c	remove:client,role:transport,type:balance	null	EXIT	(bscdw)	-	-4	-	
2016-02-19T11:47:54.168Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	IN6dq82yf6mfle/5fjojynzb98c	remove:client,role:transport,type:balance	{config:{pin:null:true},role:transport,type:balance,remove:client}	ENTRY	(bscdw)	-	-	-	
2016-02-19T11:47:54.170Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	OUT6dq82yf6mfle/5fjojynzb98c	remove:client,role:transport,type:balance	null	EXIT	(bscdw)	-	-2	-	
2016-02-19T11:47:54.242Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	INyyc0svppk5vr/5fjojynzb98c	remove:client,role:transport,type:balance	{config:{port:59740,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY	(bscdw)	-	--	
2016-02-19T11:47:54.243Z 4qf44fxmmyt4/1455882246039/302/- DEBUG	act	balance-client/mesh~us256q	OUTyyc0svppk5vr/5fjojynzb98c	remove:client,role:transport,type:balance	null	EXIT	(bscdw)	-	-1	-	
```

log from mesh base:

```
2016-02-19T11:43:42.271Z p95bum46agqn/1455882222259/32082/- INFO	hello	Seneca/1.1.0/p95bum46agqn/1455882222259/32082/-
2016-02-19T11:43:42.671Z p95bum46agqn/1455882222259/32082/- INFO	listen	{pin:role:mesh,base:true,model:actor}	
2016-02-19T11:44:09.545Z p95bum46agqn/1455882222259/32082/- INFO	client	{type:balance,pin:role: user,model:actor}	
2016-02-19T11:44:09.549Z p95bum46agqn/1455882222259/32082/- INFO	client	{type:balance,pin:role: concorda-communication,model:actor}	
2016-02-19T11:44:09.555Z p95bum46agqn/1455882222259/32082/- INFO	-	-	ACT	3iz9wotuoodo/zbhla9vxv9tg	name:mesh,plugin:define,role:seneca,seq:5,tag:undefined	plugin	mesh       	ACT	dji2d1qi28mk/83n7qotd9pyh	add:client,role:transport,type:balance	client	{port:51618,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-02-19T11:44:09.559Z p95bum46agqn/1455882222259/32082/- INFO	-	-	ACT	3iz9wotuoodo/zbhla9vxv9tg	name:mesh,plugin:define,role:seneca,seq:5,tag:undefined	plugin	mesh       	ACT	liw8smol00vm/83n7qotd9pyh	add:client,role:transport,type:balance	client	{port:51618,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	

2016-02-19T11:47:09.450Z p95bum46agqn/1455882222259/32082/- INFO	client	{type:balance,pin:null:true,model:actor}	
2016-02-19T11:47:09.457Z p95bum46agqn/1455882222259/32082/- INFO	-	-	ACT	3iz9wotuoodo/zbhla9vxv9tg	name:mesh,plugin:define,role:seneca,seq:5,tag:undefined	plugin	mesh       	ACT	agz79m7mwjfb/83n7qotd9pyh	add:client,role:transport,type:balance	client	{port:53598,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-02-19T11:47:09.776Z p95bum46agqn/1455882222259/32082/- INFO	-	-	ACT	3iz9wotuoodo/zbhla9vxv9tg	name:mesh,plugin:define,role:seneca,seq:5,tag:undefined	plugin	mesh       	ACT	yretjdntk3wb/83n7qotd9pyh	add:client,role:transport,type:balance	client	{port:59740,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-02-19T11:47:09.988Z p95bum46agqn/1455882222259/32082/- INFO	-	-	ACT	3iz9wotuoodo/zbhla9vxv9tg	name:mesh,plugin:define,role:seneca,seq:5,tag:undefined	plugin	mesh       	ACT	nxb6letj2b5c/83n7qotd9pyh	add:client,role:transport,type:balance	client	{pin:null:true,id:pin:null:true}
```

**Comment by mirceaalexandru** [comment]
If I am starting again concorda-dashboard then it works again for 2-3 requests - same behaviour without restarting base/concorda microservice

**Comment by mirceaalexandru** [comment]
seneca@1.1.0

**Comment by mirceaalexandru** [comment]
closing as not reproducible using 0.5.0
