### ISSUE TITLE
error and warning when using the readme example asyncrhonously

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca-mesh#17]
The code:
```

function base() {
  require('seneca')().use('mesh',{base:true});
}


function server() {
  var senecaServer = require('seneca')();

  senecaServer.use('mesh', { auto:true, pin:'service:fast-service' });

  senecaServer.add({ service:'fast-service', cmd:'hello' }, function (args, callback) {
    callback(null, { hello: 'world' });
  });

  senecaServer.listen();
}

function client() {
  var senecaClient = require('seneca')();

  senecaClient.use('mesh', { auto:true });

  senecaClient.act({service: 'fast-service', cmd: 'hello'}, function(err, result) {
    console.log('************', err, JSON.stringify(result, null, 2));
  });
}


base();
setTimeout(function() {
  server();
  setTimeout(function() {
    client();
  }, 1000);
}, 1000);
```

The warning and error:
```
2016-03-03T11:51:47.325Z j2wg59u0ojdc/1457005907058/17970/- WARN	act	-       	-	-	seneca: No matching action pattern found for { config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'r5c2s4wvyth8',     'default$': null,     'meta$':       { id: '6p9idoc03oey/r5c2s4wvyth8',        tx: 'r5c2s4wvyth8',        start: 1457005902159,        pattern: 'hook:listen,role:transport,type:web',        action: '(0nlwa)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).	act_not_found	{args:{ config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,    	Error: seneca: No matching action pattern found for { config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'r5c2s4wvyth8',     'default$': null,     'meta$':       { id: '6p9idoc03oey/r5c2s4wvyth8',        tx: 'r5c2s4wvyth8',        start: 1457005902159,        pattern: 'hook:listen,role:transport,type:web',        action: '(0nlwa)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).
    at Object.errormaker [as error] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/seneca/seneca.js:1054:29)
    at Immediate._onImmediate (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-03-03T11:51:47.326Z j2wg59u0ojdc/1457005907058/17970/- ERROR	act	-       	OUT		-	4	{config:{port:56317,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY		-	seneca: No matching action pattern found for { config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'r5c2s4wvyth8',     'default$': null,     'meta$':       { id: '6p9idoc03oey/r5c2s4wvyth8',        tx: 'r5c2s4wvyth8',        start: 1457005902159,        pattern: 'hook:listen,role:transport,type:web',        action: '(0nlwa)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).	act_not_found	{args:{ config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,    	Error: seneca: No matching action pattern found for { config:    { port: 56317,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'r5c2s4wvyth8',     'default$': null,     'meta$':       { id: '6p9idoc03oey/r5c2s4wvyth8',        tx: 'r5c2s4wvyth8',        start: 1457005902159,        pattern: 'hook:listen,role:transport,type:web',        action: '(0nlwa)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).
    at Object.errormaker [as error] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/seneca/seneca.js:1054:29)
    at Immediate._onImmediate (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/gate-executor/gate-executor.js:135:14)
```

The full logs:
```
2016-03-03T11:55:01.379Z rgdjiszwdafm/1457006101362/18028/- INFO	hello	Seneca/1.3.0/rgdjiszwdafm/1457006101362/18028/-	
2016-03-03T11:55:01.747Z rgdjiszwdafm/1457006101362/18028/- INFO	listen	{pin:role:mesh,base:true,model:actor}	
2016-03-03T11:55:02.670Z djsd3vi83wj3/1457006102663/18028/- INFO	hello	Seneca/1.3.0/djsd3vi83wj3/1457006102663/18028/-	
2016-03-03T11:55:02.680Z djsd3vi83wj3/1457006102663/18028/- INFO	listen		
2016-03-03T11:55:02.714Z djsd3vi83wj3/1457006102663/18028/- INFO	listen	{pin:service:fast-service,model:actor}	
2016-03-03T11:55:02.728Z rgdjiszwdafm/1457006101362/18028/- INFO	client	{type:balance,pin:null:true,model:null}	
2016-03-03T11:55:02.730Z rgdjiszwdafm/1457006101362/18028/- INFO	-	-	ACT	2u8eqp2jjrg9/mmiewfp1fb6s	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	0k8japccphpo/l7ed8abr41gh	add:client,role:transport,type:balance	client	{type:web,port:10101,host:0.0.0.0,path:null,role:transport,hook:listen,pin:null:true}	
2016-03-03T11:55:02.928Z djsd3vi83wj3/1457006102663/18028/- INFO	client	{type:balance,pin:role:mesh,base:true,model:actor}	
2016-03-03T11:55:02.937Z djsd3vi83wj3/1457006102663/18028/- WARN	act	-       	-	-	seneca: No matching action pattern found for { config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'l7ed8abr41gh',     'default$': null,     'meta$':       { id: 'fbvhig010w9q/l7ed8abr41gh',        tx: 'l7ed8abr41gh',        start: 1457006101759,        pattern: 'hook:listen,role:transport,type:web',        action: '(54z42)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).	act_not_found	{args:{ config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,    	Error: seneca: No matching action pattern found for { config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'l7ed8abr41gh',     'default$': null,     'meta$':       { id: 'fbvhig010w9q/l7ed8abr41gh',        tx: 'l7ed8abr41gh',        start: 1457006101759,        pattern: 'hook:listen,role:transport,type:web',        action: '(54z42)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).
    at Object.errormaker [as error] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/seneca/seneca.js:1054:29)
    at Immediate._onImmediate (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-03-03T11:55:02.938Z djsd3vi83wj3/1457006102663/18028/- ERROR	act	-       	OUT		-	8	{config:{port:58056,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen},role:transport,type	ENTRY		-	seneca: No matching action pattern found for { config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'l7ed8abr41gh',     'default$': null,     'meta$':       { id: 'fbvhig010w9q/l7ed8abr41gh',        tx: 'l7ed8abr41gh',        start: 1457006101759,        pattern: 'hook:listen,role:transport,type:web',        action: '(54z42)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).	act_not_found	{args:{ config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,    	Error: seneca: No matching action pattern found for { config:    { port: 58056,     model: 'actor',     type: 'web',     host: '0.0.0.0',     path: null,     role: 'transport',     hook: 'listen',     'ungate$': true,     'tx$': 'l7ed8abr41gh',     'default$': null,     'meta$':       { id: 'fbvhig010w9q/l7ed8abr41gh',        tx: 'l7ed8abr41gh',        start: 1457006101759,        pattern: 'hook:listen,role:transport,type:web',        action: '(54z42)',        entry: true,        chain: [] },     pin: 'role:mesh,base:true' },  role: 'transport',  type: 'balance',  add: 'client' }, and no default result provided (using a default$ property).
    at Object.errormaker [as error] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/seneca/seneca.js:1054:29)
    at Immediate._onImmediate (/home/nherment/workspace/nearform/seneca-mesh-test/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)	
2016-03-03T11:55:02.950Z rgdjiszwdafm/1457006101362/18028/- INFO	client	{type:balance,pin:service:fast-service,model:actor}	
2016-03-03T11:55:02.953Z rgdjiszwdafm/1457006101362/18028/- INFO	-	-	ACT	2u8eqp2jjrg9/mmiewfp1fb6s	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	mrd4z8zo2c6l/l7ed8abr41gh	add:client,role:transport,type:balance	client	{port:58096,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.151Z djsd3vi83wj3/1457006102663/18028/- INFO	-	-	ACT	z14yu2t9ty1w/gj76f5nw608z	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	9b0kriv5mq5h/8a3e8dlyyi3r	add:client,role:transport,type:balance	client	{port:58056,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.708Z ebm75ky3l8mz/1457006103707/18028/- INFO	hello	Seneca/1.3.0/ebm75ky3l8mz/1457006103707/18028/-	
2016-03-03T11:55:03.741Z ebm75ky3l8mz/1457006103707/18028/- INFO	listen	{pin:null,model:actor}	
2016-03-03T11:55:03.749Z rgdjiszwdafm/1457006101362/18028/- INFO	-	-	ACT	2u8eqp2jjrg9/mmiewfp1fb6s	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	8vg8ir7b1w19/l7ed8abr41gh	add:client,role:transport,type:balance	client	{port:50763,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.789Z djsd3vi83wj3/1457006102663/18028/- INFO	client	{type:balance,pin:null:true,model:actor}	
2016-03-03T11:55:03.790Z djsd3vi83wj3/1457006102663/18028/- INFO	-	-	ACT	z14yu2t9ty1w/gj76f5nw608z	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	znxbm1sbxxe5/0xigd5xrfy6l	add:client,role:transport,type:balance	client	{port:50763,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.856Z djsd3vi83wj3/1457006102663/18028/- INFO	-	-	ACT	z14yu2t9ty1w/gj76f5nw608z	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	dskveosphn3e/8a3e8dlyyi3r	add:client,role:transport,type:balance	client	{port:50763,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.949Z ebm75ky3l8mz/1457006103707/18028/- INFO	client	{type:balance,pin:null:true,model:null}	
2016-03-03T11:55:03.950Z ebm75ky3l8mz/1457006103707/18028/- INFO	client	{type:balance,pin:service:fast-service,model:actor}	
2016-03-03T11:55:03.951Z ebm75ky3l8mz/1457006103707/18028/- INFO	client	{type:balance,pin:role:mesh,base:true,model:actor}	
2016-03-03T11:55:03.952Z ebm75ky3l8mz/1457006103707/18028/- INFO	-	-	ACT	da1p89kvd83s/4k2r3u45qacj	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	tnh2xavpd0e8/fnwxwxx48oyr	add:client,role:transport,type:balance	client	{type:web,port:10101,host:0.0.0.0,path:null,role:transport,hook:listen,pin:null:true}	
2016-03-03T11:55:03.953Z ebm75ky3l8mz/1457006103707/18028/- INFO	-	-	ACT	da1p89kvd83s/4k2r3u45qacj	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	oe9wumbt347w/fnwxwxx48oyr	add:client,role:transport,type:balance	client	{port:58096,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
2016-03-03T11:55:03.954Z ebm75ky3l8mz/1457006103707/18028/- INFO	-	-	ACT	da1p89kvd83s/4k2r3u45qacj	name:mesh,plugin:define,role:seneca,seq:6,tag:undefined	plugin	mesh       	ACT	vzaq4dij74q0/fnwxwxx48oyr	add:client,role:transport,type:balance	client	{port:58056,model:actor,type:web,host:0.0.0.0,path:null,role:transport,hook:listen}	
************ null {
  "hello": "world"
}
```

**Comment by mcdonnelldean** [comment]
@nherment I think there was issues with the last version, `0.7.0` should work here.

**Comment by nherment** [comment]
sorry, we are not using mesh anymore and I don't have the bandwidth to test this again. Should there just be a test covering this ?

**Comment by mcdonnelldean** [comment]
@nherment Sounds like a good idea.

**Comment by rjrodger** [comment]
mesh now uses plugin init functions, so seneca.ready should solve this
