### ISSUE TITLE
no longer works with currently released seneca

### ISSUE THREAD

**Issue by AdrianRossouw** [rjrodger/seneca-mesh#21]
The currently released version of this package is dependent on seneca master branch.

This is the error:
```
seneca: Action cmd:listen,role:transport callback threw: seneca.util.pincanon is not a function.	act_callback	{message:seneca.util.pincanon is not a function,pattern:cmd:listen,role:transport,instance:Seneca/1.3.0/4v/-,pl	TypeError: seneca.util.pincanon is not a function
    at join (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca-mesh/mesh.js:95:19)
    at Seneca.<anonymous> (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca-mesh/mesh.js:78:7)
    at act_done (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca/seneca.js:1220:21)
    at Seneca.<anonymous> (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca/node_modules/gate-executor/gate-executor.js:155:20)
    at act_done (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca/seneca.js:1220:21)
    at /Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca/node_modules/gate-executor/gate-executor.js:155:20
    at Server.<anonymous> (/Users/adrian/Projects/nearform/nodezoo-search/node_modules/seneca/node_modules/seneca-transport/lib/http.js:52:7)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1262:10)	
```

**Comment by m3l7** [comment]
Happens with me too, version 0.6 and 0.7

**Comment by AdrianRossouw** [comment]
we ended up falling back to seneca-mesh@0.5.0 and seneca-balance-client@0.2.0 and it works again.

**Comment by m3l7** [comment]
confirmed

**Comment by rjrodger** [comment]
my bad! seneca 1.4.0 is due out wednesday and will correct this
/cc @naomifeehanmoran

**Comment by AdrianRossouw** [comment]
1.4.0 was released. closing.
